package co.edu.unicauca.lisw2t5g02.access;
import co.edu.unicauca.lisw2t5g02.domain.question.*;import co.edu.unicauca.lisw2t5g02.domain.question.Question.EstadoPregunta;import java.sql.*;import java.util.*;
public class QuestionImplRepository implements QuestionRepository {private static final String URL_BD="jdbc:sqlite:preguntas.db";public QuestionImplRepository(){init();}private Connection c()throws SQLException{return DriverManager.getConnection(URL_BD);}private void init(){try(Connection c=c();Statement s=c.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS pregunta(id TEXT PRIMARY KEY,nombre TEXT NOT NULL,contexto TEXT,preguntaDirecta TEXT NOT NULL,justificacion TEXT,bibliografia TEXT,competencia TEXT,tema TEXT,subtema TEXT,nivelDificultad TEXT,respuestaCorrecta TEXT NOT NULL,estado TEXT NOT NULL,autorId INTEGER NOT NULL DEFAULT 0)");try{s.execute("ALTER TABLE pregunta ADD COLUMN contexto TEXT");}catch(SQLException ignored){}try{s.execute("ALTER TABLE pregunta ADD COLUMN preguntaDirecta TEXT");}catch(SQLException ignored){}try{s.execute("ALTER TABLE pregunta ADD COLUMN justificacion TEXT");}catch(SQLException ignored){}try{s.execute("ALTER TABLE pregunta ADD COLUMN bibliografia TEXT");}catch(SQLException ignored){}try{s.execute("ALTER TABLE pregunta ADD COLUMN competencia TEXT");}catch(SQLException ignored){}try{s.execute("ALTER TABLE pregunta ADD COLUMN tema TEXT");}catch(SQLException ignored){}try{s.execute("ALTER TABLE pregunta ADD COLUMN subtema TEXT");}catch(SQLException ignored){}try{s.execute("ALTER TABLE pregunta ADD COLUMN nivelDificultad TEXT");}catch(SQLException ignored){}try{s.execute("ALTER TABLE pregunta ADD COLUMN autorId INTEGER NOT NULL DEFAULT 0");}catch(SQLException ignored){}s.execute("CREATE TABLE IF NOT EXISTS opcion(idPregunta TEXT NOT NULL,letra TEXT NOT NULL,texto TEXT NOT NULL,FOREIGN KEY(idPregunta) REFERENCES pregunta(id))");s.execute("CREATE TABLE IF NOT EXISTS pregunta_revisor(idPregunta TEXT NOT NULL,idRevisor INTEGER NOT NULL,PRIMARY KEY(idPregunta,idRevisor))");seed(c);}catch(SQLException e){throw new RuntimeException("Error inicializando SQLite",e);}}
 private void seed(Connection c)throws SQLException{try(ResultSet r=c.createStatement().executeQuery("SELECT COUNT(*) FROM pregunta")){if(r.next()&&r.getInt(1)==0){insertSeed(c,"P-001","Razonamiento cuantitativo","En una universidad se registran 240 estudiantes y el 35% participa en un programa de apoyo.","¿Cuántos estudiantes participan en el programa de apoyo?","84","Borrador",new String[]{"72","84","96","108","120"});insertSeed(c,"P-002","Comprensión lectora","Un informe explica que una medida redujo los tiempos de espera, pero aumentó los costos operativos.","¿Cuál conclusión está respaldada directamente por el texto?","La medida redujo los tiempos de espera y aumentó los costos operativos.","Pendiente de revisión",new String[]{"La medida redujo los tiempos de espera y aumentó los costos operativos.","La medida eliminó todos los costos.","La medida no produjo ningún cambio.","Los tiempos de espera aumentaron.","El informe no presenta resultados."});}}}
 private void insertSeed(Connection c,String id,String n,String ctx,String q,String correct,String state,String[] opts)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO pregunta(id,nombre,contexto,preguntaDirecta,justificacion,bibliografia,competencia,tema,subtema,nivelDificultad,respuestaCorrecta,estado,autorId) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)")){p.setString(1,id);p.setString(2,n);p.setString(3,ctx);p.setString(4,q);p.setString(5,"La respuesta se obtiene directamente al relacionar la información del contexto con la pregunta.");p.setString(6,"Material de referencia del curso.");p.setString(7,"Interpretación y análisis");p.setString(8,"Razonamiento");p.setString(9,"Interpretación de información");p.setString(10,"Intermedio");p.setString(11,correct);p.setString(12,state);p.setInt(13,0);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT INTO opcion VALUES(?,?,?)")){char l='A';for(String o:opts){p.setString(1,id);p.setString(2,""+l++);p.setString(3,o);p.addBatch();}p.executeBatch();}}
 public void guardar(Question p){String sql="INSERT INTO pregunta(id,nombre,contexto,preguntaDirecta,justificacion,bibliografia,competencia,tema,subtema,nivelDificultad,respuestaCorrecta,estado,autorId) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";try(Connection c=c();PreparedStatement s=c.prepareStatement(sql)){set(s,p);s.executeUpdate();guardarOpciones(c,p);}catch(SQLException e){throw new RuntimeException("Error guardando pregunta",e);}}
 private void set(PreparedStatement s,Question p)throws SQLException{s.setString(1,p.getId());s.setString(2,p.getNombre());s.setString(3,p.getContexto());s.setString(4,p.getPreguntaDirecta());s.setString(5,p.getJustificacion());s.setString(6,p.getBibliografia());s.setString(7,p.getCompetencia());s.setString(8,p.getTema());s.setString(9,p.getSubtema());s.setString(10,p.getNivelDificultad());s.setString(11,p.getRespuestaCorrecta());s.setString(12,p.getEstado().getEtiqueta());s.setInt(13,p.getAutorId());}
 private void guardarOpciones(Connection c,Question p)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO opcion VALUES(?,?,?)")){for(QuestionDistractors o:p.getOpciones()){s.setString(1,p.getId());s.setString(2,o.getLetra());s.setString(3,o.getTexto());s.addBatch();}s.executeBatch();}}
 public Question obtenerPorId(String id){try(Connection c=c();PreparedStatement s=c.prepareStatement("SELECT * FROM pregunta WHERE id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){return r.next()?map(c,r):null;}}catch(SQLException e){throw new RuntimeException("Error consultando pregunta",e);}}
 private Question map(Connection c,ResultSet r)throws SQLException{Question p=new Question(r.getString("id"),r.getString("nombre"),r.getString("preguntaDirecta"),r.getString("respuestaCorrecta"),EstadoPregunta.fromEtiqueta(r.getString("estado")));p.setContexto(r.getString("contexto"));p.setPreguntaDirecta(r.getString("preguntaDirecta"));p.setJustificacion(r.getString("justificacion"));p.setBibliografia(r.getString("bibliografia"));p.setCompetencia(r.getString("competencia"));p.setTema(r.getString("tema"));p.setSubtema(r.getString("subtema"));p.setNivelDificultad(r.getString("nivelDificultad"));p.setAutorId(r.getInt("autorId"));try(PreparedStatement s=c.prepareStatement("SELECT letra,texto FROM opcion WHERE idPregunta=? ORDER BY letra")){s.setString(1,p.getId());try(ResultSet o=s.executeQuery()){while(o.next())p.agregarOpcion(new QuestionDistractors(o.getString(1),o.getString(2)));}}return p;}
 public List<Question> obtenerTodas(){return query("SELECT * FROM pregunta ORDER BY rowid",new Object[0]);}
 public List<Question> obtenerPorAutor(int autorId,EstadoPregunta estado,int page,int size){asegurarDatosDemoParaAutor(autorId);String sql="SELECT * FROM pregunta WHERE "+(autorId<0?"1=1":"autorId=?");List<Object> a=new ArrayList<>();if(autorId>=0)a.add(autorId);if(estado!=null){sql+=" AND estado=?";a.add(estado.getEtiqueta());}sql+=" ORDER BY rowid LIMIT ? OFFSET ?";a.add(size);a.add(page*size);return query(sql,a.toArray());}
 @Override public List<Question> obtenerTodasFiltradas(EstadoPregunta estado,int page,int size){String sql="SELECT * FROM pregunta";List<Object> a=new ArrayList<>();if(estado!=null){sql+=" WHERE estado=?";a.add(estado.getEtiqueta());}sql+=" ORDER BY rowid LIMIT ? OFFSET ?";a.add(size);a.add(page*size);return query(sql,a.toArray());}
 @Override public int contarTodas(EstadoPregunta estado){String sql="SELECT COUNT(*) FROM pregunta"+(estado!=null?" WHERE estado=?":"");try(Connection c=c();PreparedStatement s=c.prepareStatement(sql)){if(estado!=null)s.setString(1,estado.getEtiqueta());try(ResultSet r=s.executeQuery()){r.next();return r.getInt(1);}}catch(SQLException e){throw new RuntimeException(e);}}
 public int contarPorAutor(int autorId,EstadoPregunta estado){asegurarDatosDemoParaAutor(autorId);String sql="SELECT COUNT(*) FROM pregunta WHERE "+(autorId<0?"1=1":"autorId=?");try(Connection c=c();PreparedStatement s=c.prepareStatement(sql+(estado!=null?" AND estado=?":""))){int i=1;if(autorId>=0)s.setInt(i++,autorId);if(estado!=null)s.setString(i,estado.getEtiqueta());try(ResultSet r=s.executeQuery()){r.next();return r.getInt(1);}}catch(SQLException e){throw new RuntimeException(e);}}
 private void asegurarDatosDemoParaAutor(int autorId){if(autorId<=0)return;try(Connection c=c();PreparedStatement q=c.prepareStatement("SELECT COUNT(*) FROM pregunta WHERE autorId=?")){q.setInt(1,autorId);try(ResultSet r=q.executeQuery()){r.next();if(r.getInt(1)==0){try(PreparedStatement u=c.prepareStatement("UPDATE pregunta SET autorId=? WHERE autorId=0")){u.setInt(1,autorId);u.executeUpdate();}}}}catch(SQLException e){throw new RuntimeException("Error asignando preguntas demo al autor",e);}}
 private List<Question> query(String sql,Object[] a){List<Question> l=new ArrayList<>();try(Connection c=c();PreparedStatement s=c.prepareStatement(sql)){for(int i=0;i<a.length;i++)s.setObject(i+1,a[i]);try(ResultSet r=s.executeQuery()){while(r.next())l.add(map(c,r));}}catch(SQLException e){throw new RuntimeException("Error listando preguntas",e);}return l;}
 public void actualizarEstado(String id,EstadoPregunta estado){try(Connection c=c();PreparedStatement s=c.prepareStatement("UPDATE pregunta SET estado=? WHERE id=?")){s.setString(1,estado.getEtiqueta());s.setString(2,id);s.executeUpdate();}catch(SQLException ex){throw new RuntimeException(ex);}}
 public void actualizar(Question p){try(Connection c=c();PreparedStatement s=c.prepareStatement("UPDATE pregunta SET nombre=?,contexto=?,preguntaDirecta=?,justificacion=?,bibliografia=?,competencia=?,tema=?,subtema=?,nivelDificultad=?,respuestaCorrecta=?,estado=? WHERE id=?")){s.setString(1,p.getNombre());s.setString(2,p.getContexto());s.setString(3,p.getPreguntaDirecta());s.setString(4,p.getJustificacion());s.setString(5,p.getBibliografia());s.setString(6,p.getCompetencia());s.setString(7,p.getTema());s.setString(8,p.getSubtema());s.setString(9,p.getNivelDificultad());s.setString(10,p.getRespuestaCorrecta());s.setString(11,p.getEstado().getEtiqueta());s.setString(12,p.getId());s.executeUpdate();try(PreparedStatement d=c.prepareStatement("DELETE FROM opcion WHERE idPregunta=?")){d.setString(1,p.getId());d.executeUpdate();}guardarOpciones(c,p);}catch(SQLException e){throw new RuntimeException("Error actualizando pregunta",e);}}
 public void asignarRevisores(String id,List<Integer> ids){try(Connection c=c()){try(PreparedStatement d=c.prepareStatement("DELETE FROM pregunta_revisor WHERE idPregunta=?")){d.setString(1,id);d.executeUpdate();}try(PreparedStatement s=c.prepareStatement("INSERT INTO pregunta_revisor VALUES(?,?)")){for(Integer x:ids){s.setString(1,id);s.setInt(2,x);s.addBatch();}s.executeBatch();}}catch(SQLException e){throw new RuntimeException("Error asignando revisores",e);}}
 public List<Integer> obtenerRevisores(String id){List<Integer> l=new ArrayList<>();try(Connection c=c();PreparedStatement s=c.prepareStatement("SELECT idRevisor FROM pregunta_revisor WHERE idPregunta=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){while(r.next())l.add(r.getInt(1));}}catch(SQLException e){throw new RuntimeException(e);}return l;}
 public Map<EstadoPregunta,Integer> contarPorEstado(){Map<EstadoPregunta,Integer>m=new LinkedHashMap<>();for(EstadoPregunta e:EstadoPregunta.values())m.put(e,0);for(Question q:obtenerTodas())m.put(q.getEstado(),m.get(q.getEstado())+1);return m;}
}
