package co.edu.unicauca.lisw2t5g02.access;
import co.edu.unicauca.lisw2t5g02.domain.user.*;import java.sql.*;import java.util.*;import java.util.logging.*;
public class SQLiteUserRepository implements IUserRepository {private static final Logger LOGGER=Logger.getLogger(SQLiteUserRepository.class.getName());private final String jdbcUrl;public SQLiteUserRepository(String dbPath){jdbcUrl="jdbc:sqlite:"+dbPath;initSchema();}private Connection connect()throws SQLException{return DriverManager.getConnection(jdbcUrl);}private void initSchema(){try(Connection c=connect();Statement s=c.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS usuario (usu_id INTEGER PRIMARY KEY, usu_usuario VARCHAR(50) NOT NULL UNIQUE, usu_nombre VARCHAR(100) NOT NULL, usu_email VARCHAR(150), usu_rol VARCHAR(30) NOT NULL, usu_estado VARCHAR(15) NOT NULL, password VARCHAR(255) NOT NULL)");try{ s.execute("ALTER TABLE usuario ADD COLUMN usu_email VARCHAR(150)"); }catch(SQLException ignored){}}catch(SQLException e){throw new RuntimeException("Error inicializando usuarios",e);}}
 public void create(User u){String sql="INSERT INTO usuario(usu_usuario,usu_nombre,usu_email,usu_rol,usu_estado,password) VALUES(?,?,?,?,?,?)";try(Connection c=connect();PreparedStatement p=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){p.setString(1,u.getUsername());p.setString(2,u.getName());p.setString(3,u.getEmail());p.setString(4,u.getRole().getDbValue());p.setString(5,u.getState().getDbValue());p.setString(6,u.getPasswordHash());p.executeUpdate();try(ResultSet k=p.getGeneratedKeys()){if(k.next())u.setId(k.getInt(1));}}catch(SQLException e){throw new RuntimeException("Error creando usuario",e);}}
 public Optional<User> findByUsername(String n){return find("SELECT * FROM usuario WHERE usu_usuario=?",n);} public Optional<User> findById(int id){return find("SELECT * FROM usuario WHERE usu_id=?",id);} private Optional<User> find(String sql,Object x){try(Connection c=connect();PreparedStatement p=c.prepareStatement(sql)){p.setObject(1,x);try(ResultSet r=p.executeQuery()){if(r.next())return Optional.of(map(r));}}catch(SQLException e){throw new RuntimeException("Error consultando usuarios",e);}return Optional.empty();}
 public List<User> listAll(){List<User> l=new ArrayList<>();try(Connection c=connect();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT * FROM usuario ORDER BY usu_id")){while(r.next())l.add(map(r));}catch(SQLException e){throw new RuntimeException("Error listando usuarios",e);}return l;}
 public void update(User u){String sql="UPDATE usuario SET usu_usuario=?,usu_nombre=?,usu_email=?,usu_rol=?,usu_estado=?,password=? WHERE usu_id=?";try(Connection c=connect();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,u.getUsername());p.setString(2,u.getName());p.setString(3,u.getEmail());p.setString(4,u.getRole().getDbValue());p.setString(5,u.getState().getDbValue());p.setString(6,u.getPasswordHash());p.setInt(7,u.getId());p.executeUpdate();}catch(SQLException e){throw new RuntimeException("Error actualizando usuario",e);}}
 public void delete(int id){try(Connection c=connect();PreparedStatement p=c.prepareStatement("DELETE FROM usuario WHERE usu_id=?")){p.setInt(1,id);p.executeUpdate();}catch(SQLException e){throw new RuntimeException("Error eliminando usuario",e);}}
 private User map(ResultSet r)throws SQLException{User u=new User();u.setId(r.getInt("usu_id"));u.setUsername(r.getString("usu_usuario"));u.setName(r.getString("usu_nombre"));u.setEmail(r.getString("usu_email"));u.setRole(Role.fromDbValue(r.getString("usu_rol")));u.setState(UserState.fromDbValue(r.getString("usu_estado")));u.setPasswordHash(r.getString("password"));return u;}}
