question.multiplechoice=co.edu.unicauca.microkernel.plugins.MultipleChoiceQuestionPlugin
question.case=co.edu.unicauca.microkernel.plugins.CaseQuestionPlugin
question.multimedia=co.edu.unicauca.microkernel.plugins.MultimediaQuestionPlugin
